INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '男', '0', 'sys_user_sex', '', '', 'Y', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '性别男');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '女', '1', 'sys_user_sex', '', '', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '性别女');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 3, '未知', '2', 'sys_user_sex', '', '', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '性别未知');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '显示', '0', 'sys_show_hide', '', 'primary', 'Y', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '显示菜单');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '隐藏', '1', 'sys_show_hide', '', 'danger', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '隐藏菜单');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '正常', '0', 'sys_normal_disable', '', 'primary', 'Y', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '正常状态');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '停用', '1', 'sys_normal_disable', '', 'danger', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '停用状态');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '是', 'Y', 'sys_yes_no', '', 'primary', 'Y', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '系统默认是');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '否', 'N', 'sys_yes_no', '', 'danger', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '系统默认否');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '存在', '存在', 'sys_del', '', 'primary', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '删除标志：存在');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '删除', '删除', 'sys_del', '', 'danger', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '删除标志：删除');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '离线', '离线', 'sys_device_join', '', 'danger', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '设备连接状态：离线');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '在线', '在线', 'sys_device_join', '', 'primary', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '设备连接状态：在线');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '未知', '未知', 'sys_device_out', '', 'danger', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '设备注销状态：未知');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '已注销', '已注销', 'sys_device_out', '', 'danger', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '设备连接状态：已注销');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 3, '在线', '在线', 'sys_device_out', '', 'primary', 'N', '0', 'admin', '2024-11-15 11:37:45', 'admin', '2024-11-15 11:37:45', '设备连接状态：在线');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '开启', '1', 'sys_zlm_close', '', '', 'Y', '0', 'admin', '2024-11-15 16:01:11', 'admin', '2024-11-15 16:01:11', '流状态 开启 关闭');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '关闭', '2', 'sys_zlm_close', '', '', 'N', '0', 'admin', '2024-11-15 16:01:11', 'admin', '2024-11-15 16:01:11', '流状态 开启 关闭');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, 'UDP', 'UDP', 'sys_stream_transport', '', '', 'Y', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', '点播流协议');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, 'TCP-ACTIVE', 'TCP-ACTIVE', 'sys_stream_transport', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', '点播流协议');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 3, 'TCP-PASSIVE', 'TCP-PASSIVE', 'sys_stream_transport', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', '点播流协议');

INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '海康', '海康', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}:554/ch1/main/av_stream');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '中威摄像机', '中威摄像机', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}:554/Streaming/Channels/1');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '萤石云', '萤石云', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}:554/Streaming/Channels/101');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '大华', '大华', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}:554/cam/realmonitor?channel=1&subtype=0');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '英飞拓', '英飞拓', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}:554/1/h264major');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '三星', '三星', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}:554/onvif/profile2/media.smp');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '宇视', '宇视', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}/media/video1/multicast');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, 'LG', 'LG', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}:554/Master-0');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '派尔高网络摄像机', '派尔高网络摄像机', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}/h264');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '安讯士网络摄像机', '安讯士网络摄像机', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}/axis-media/media.amp?videocodec=h264&resolution=1280x720&fps=25');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '非凡', '非凡', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}:554/streaming/channels/101');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 999, '金三立', '金三立', 'sys_manufacturer', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', 'rtsp://${username}:${password}@${ip}/stream/av0_0');

INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '摄像头', '摄像头', 'sys_media_type', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', '媒体播放类型');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '文件', '文件', 'sys_media_type', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', '媒体播放类型');
INSERT INTO `sys_dict` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 3, '网络URL', '网络URL', 'sys_media_type', '', '', 'N', '0', 'admin', '2024-11-19 15:43:45', 'admin', '2024-11-19 15:43:45', '媒体播放类型');


